# Generated by Django 3.2.9 on 2022-01-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_store',
            field=models.CharField(max_length=50),
        ),
    ]
